### ISSUE TITLE
Listener stops responding to new links after some time

### ISSUE THREAD

**Issue by acehoss** [acehoss/rnsh#10]
Without fail, the listener stops responding to new links after an hour or so. I'm not sure if the time is specific or random, but it seems to always happen. This is the same issue that caused #9.

1. Start/Restart the listener
2. Connect and it works fine
3. Disconnect and leave it idle for least 30 minutes
4. Can't connect anymore

**Comment by acehoss** [comment]
After further testing, I don't think this is a problem with the listener. I think the application is actually timing out waiting for a path. A loop to try a few times might be needed. It would probably be helpful to add back in the spinner and status messages from the `rnx` code to help clue the user in.

What I've noticed is that if it fails to connect, I can try a couple more times and it eventually does connect. 🤔

**Comment by markqvist** [comment]
Hmm, that is strange... I will try looking a bit into this as well.

**Comment by acehoss** [comment]
I have a little more information on this. It seems to be related to the number of hops involved. When I set up a direct connection to the RNS instance on the BBS server, I no longer had connection issues.

![Network Diagram](https://user-images.githubusercontent.com/5148966/220616248-ad281cff-d52f-46d5-a24b-123cb7af7cc9.png)

**Comment by markqvist** [comment]
Hmm, I wonder if this could be caused by the path running over the I2P links initially, and then something causing those to become unavailable, after which the connection fails (probably until a new announce is sent, re-establishing the path over the TCP links).

I have seen weird flapping going on with the I2P interfaces at times, but haven't been able to narrow it down to anything concrete yet.

**Comment by acehoss** [comment]
After a lot of testing, this does indeed appear to be due to delays in path discovery. It's just part of running on Reticulum.
